### ISSUE TITLE
Home page re-design

### ISSUE THREAD

**Issue by sbunciak** [redhatcz/Thesis-management-system#102]
- Include searchable list of topics, with a tag cloud
- Include General information about the portal

**Comment by sbunciak** [comment]
* Modify CSS to match Red Hat colors

**Comment by sbunciak** [comment]
Here is a mock of the potential new home page:
![page 1](https://cloud.githubusercontent.com/assets/1398742/17550665/5a3da120-5ef6-11e6-8478-3fee4c79f193.png)

Available here: http://ninjamock.com/s/9STVD

Please provide feedback/questions.

**Comment by VaclavDedik** [comment]
I like it, just a bit worried the page will look a bit odd if there isn't enough text. So hopefully there will be enough to fill the page.

**Comment by jcechace** [comment]
Exactly what Vaclav said.  The search box is a good idea,  contact for Mato as well. Maybe we could still have  something like last 5 added topics? Or maybe something like "topics highlights"  if we wanted to promote certain topics?

**Comment by sbunciak** [comment]
@VaclavDedik there should be enough text, at least that's Matej's job to deliver :)
@jcechace I don't see much point in displaying latest topics, but I like the idea of highlighting "featured" topics. Definitely +1 to provide something like that in the topic listing.

**Comment by TheSprtCz** [comment]
Done in #130.
