### ISSUE TITLE
Allow registration mail filter to operate over 2nd level domains 

### ISSUE THREAD

**Issue by jcechace** [redhatcz/Thesis-management-system#58]
Currently we need the exact domain name to be white-listed for registration. This is very inconvenient as usually universities are providing email address on various different subdomains. Consequently we need to whitelist  all domain names such as "fi.muni.cz", "mail.muni.cz" and so on.   

I propose we change the filters in way that whitelisting 2nd level domain would be sufficient (e.g. "muni.cz") or allow usage of some wildcard character (e.g. "*.mail.muni.cz")

**Comment by VaclavDedik** [comment]
Fixed by #116
