### ISSUE TITLE
500 Internal Server Error report upon application creation

### ISSUE THREAD

**Issue by chudikj** [redhatcz/Thesis-management-system#74]
After submitting an application to a particular topic, I got both a message saying that it was successfully created and an error report. This might be a source of confusion for the applying student, since it's unclear whether their application actually got into the system or not. It might cause significant stress or even paranoia as they question the validity of their application (or it could lead to spamming the system multiple times with the same application) since the application does not appear in their profile, under the Applications tab.

![server_error](https://cloud.githubusercontent.com/assets/8931337/4424630/5b0feb64-45a1-11e4-8a59-8c2cc04dca8b.jpg)
(Here's a link to the topic in question, in case it doesn't occur anywhere else: https://thesis-managementsystem.rhcloud.com/topic/show/223/firefox-os-application)

**Comment by VaclavDedik** [comment]
Fixed by #82
